# GitHub Actions workflow to build HTML site via Sphinx and deploy it
# to github.io via the gh-pages branch
#
# Primarily based on https://github.com/marketplace/actions/sphinx-docs-to-github-pages

name: Sphinx website to gh-pages

on:
  push:
    branches:
      - main

jobs:
  sphinx_website_to_gh-pages:
    name: Sphinx website to gh-pages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
           miniforge-variant: Mambaforge-pypy3
           miniforge-version: latest
           use-mamba: true
           auto-update-conda: false
           auto-activate-base: false
           channels: conda-forge,nodefaults
           channel-priority: true
           environment-file: envs/environment-gh-pages.yaml
           activate-environment: numeric-gh-pages

      - name: Sphinx build and deploy
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
        with:
          branch: main
          dir_docs: website
          sphinxopts: ''
